"""Cloudflare Pages provider.

Cloudflare API: POST /accounts/{id}/pages/projects (Direct Upload project) ->
repository gets CLOUDFLARE_API_TOKEN / CLOUDFLARE_ACCOUNT_ID as encrypted Actions secrets ->
.github/workflows/clouddeploy-cloudflare.yml builds and runs `wrangler pages deploy` (Cloudflare's
official CLI) -> deployment + URL read back from the Cloudflare API.
"""
from __future__ import annotations

from datetime import datetime, timezone

import httpx

from backend.config import settings
from backend.models import Deployment
from backend.services.deployment.actions import ActionsRunTracker, build_steps
from backend.services.deployment.base import (
    PHASE_FAILED,
    PHASE_LIVE,
    DeployContext,
    DeployError,
    DeployHandle,
    DeploymentProvider,
    LogLine,
    ProviderStatus,
    slugify,
    unique_slug,
)
from backend.services.github.client import GitHubClient
from backend.services.http import DEFAULT_TIMEOUT, ApiError, request

API = "https://api.cloudflare.com/client/v4"
WORKFLOW_FILE = "clouddeploy-cloudflare.yml"
WORKFLOW_PATH = f".github/workflows/{WORKFLOW_FILE}"
STATIC_TYPES = {"Static Frontend", "Frontend", "Serverless"}


class CloudflarePagesProvider(DeploymentProvider):
    key = "cloudflare_pages"

    def __init__(self, token_getter):
        self._token_getter = token_getter  # (user_id) -> str | None
        self._tracker = ActionsRunTracker(lambda dep: GitHubClient(self._token_getter(dep.user_id)))

    def missing_credentials(self) -> list[str]:
        missing = [n for n, v in (("CLOUDFLARE_API_TOKEN", settings.cloudflare_api_token),
                                  ("CLOUDFLARE_ACCOUNT_ID", settings.cloudflare_account_id)) if not v]
        return missing

    def _client(self) -> httpx.AsyncClient:
        return httpx.AsyncClient(
            base_url=f"{API}/accounts/{settings.cloudflare_account_id}", timeout=DEFAULT_TIMEOUT,
            headers={"Authorization": f"Bearer {settings.cloudflare_api_token}"},
        )

    async def check_credentials(self, user_id: int | None = None) -> dict:
        if not (settings.cloudflare_api_token and settings.cloudflare_account_id):
            return {"ok": False, "account": None, "error": "Provider Not Configured"}
        try:
            async with self._client() as client:
                await request(client, "Cloudflare", "GET", "/pages/projects", params={"per_page": 1})
            return {"ok": True, "account": settings.cloudflare_account_id, "error": None}
        except ApiError as exc:
            return {"ok": False, "account": None, "error": str(exc)}

    def workflow(self, ctx: DeployContext, project_name: str, branch: str) -> str:
        steps, out = build_steps(ctx)
        lines = [
            "# Generated by Git2Live: builds this repository and deploys it to Cloudflare Pages.",
            "name: Git2Live · Cloudflare Pages",
            "on:",
            "  workflow_dispatch:",
            "permissions:",
            "  contents: read",
            "jobs:",
            "  deploy:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            *steps,
            *([] if any("setup-node" in s for s in steps) else [
                "      - uses: actions/setup-node@v4",
                "        with:",
                "          node-version: 20",
            ]),
            "      - name: Deploy with wrangler",
            f"        run: npx --yes wrangler@4 pages deploy \"{out}\" --project-name={project_name} --branch={branch} --commit-dirty=true",
            "        env:",
            "          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}",
            "          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}",
        ]
        return "\n".join(lines) + "\n"

    def validate(self, ctx: DeployContext) -> tuple[list[str], list[str]]:
        errors, warnings = [], []
        if not ctx.github.authenticated:
            errors.append("Connect GitHub first. Cloudflare Pages deploys run in your repository's GitHub Actions.")
        if not ctx.project.repository:
            errors.append("This integration builds with GitHub Actions. Publish this project to GitHub first.")
        if ctx.analysis.get("app_type") not in STATIC_TYPES:
            errors.append("Cloudflare Pages cannot run a long-running backend server.")
        warnings.append("Your Cloudflare API token will be stored as an encrypted GitHub Actions secret in this repository.")
        if ctx.config.env_vars:
            warnings.append("Environment variables are not sent to Cloudflare in this version.")
        return errors, warnings

    def preview(self, ctx: DeployContext) -> dict:
        branch = ctx.config.branch or ctx.project.branch or "main"
        name = ctx.previous_meta.get("cf_project") or slugify(ctx.config.name or ctx.project.name, 58)
        return {
            "resource": "Cloudflare Pages project (Direct Upload via wrangler)",
            "plan": "Free",
            "build": "GitHub Actions + wrangler pages deploy",
            "build_command": ctx.pick("build_command") or "none (static files)",
            "output_dir": ctx.pick("output_dir") or ".",
            "generated_workflow": self.workflow(ctx, name, branch) if ctx.project.repository else None,
            "repository_changes": [WORKFLOW_PATH, "Actions secrets: CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID"],
        }

    async def _create_project(self, client: httpx.AsyncClient, ctx: DeployContext, branch: str) -> dict:
        base = ctx.config.name or ctx.project.name
        for name in (slugify(base, 58), unique_slug(base, 58), unique_slug(base, 58)):
            try:
                resp = await request(client, "Cloudflare", "POST", "/pages/projects", json={"name": name, "production_branch": branch})
                return resp.json()["result"]
            except ApiError as exc:
                if exc.status not in (400, 409) or "exist" not in exc.message.lower():
                    raise
        raise DeployError("Could not find an available Cloudflare Pages project name.", "Choose a different deployment name.")

    async def deploy(self, ctx: DeployContext) -> DeployHandle:
        self.require_configured()
        p = ctx.project
        branch = ctx.config.branch or p.branch or "main"
        try:
            async with self._client() as client:
                name = ctx.previous_meta.get("cf_project")
                subdomain = ctx.previous_meta.get("subdomain")
                if not name:
                    project = await self._create_project(client, ctx, branch)
                    name, subdomain = project["name"], project.get("subdomain")
                    ctx.log(f"Created Cloudflare Pages project '{name}' ({subdomain})")
            ctx.log("Storing Cloudflare credentials as encrypted GitHub Actions secrets")
            await ctx.github.set_secret(p.github_owner, p.github_repo, "CLOUDFLARE_API_TOKEN", settings.cloudflare_api_token)
            await ctx.github.set_secret(p.github_owner, p.github_repo, "CLOUDFLARE_ACCOUNT_ID", settings.cloudflare_account_id)
            ctx.log(f"Committing {WORKFLOW_PATH} to {branch}")
            await ctx.github.put_file(
                p.github_owner, p.github_repo, WORKFLOW_PATH, self.workflow(ctx, name, branch),
                "Add Git2Live Cloudflare Pages workflow", branch,
            )
            dispatched_at = datetime.now(timezone.utc)
            run_id = await ctx.github.dispatch_workflow(p.github_owner, p.github_repo, WORKFLOW_FILE, branch)
            ctx.log("Workflow dispatched" + (f" (run {run_id})" if run_id else ""))
        except ApiError as exc:
            fix = None
            if exc.service == "Cloudflare" and exc.status in (401, 403):
                fix = "Check that CLOUDFLARE_API_TOKEN has the 'Cloudflare Pages: Edit' permission and CLOUDFLARE_ACCOUNT_ID is correct."
            elif exc.service == "GitHub" and exc.status in (403, 404):
                fix = "Reconnect GitHub and grant repo and workflow permissions (admin access is needed to set secrets)."
            raise DeployError(f"{exc.service} rejected the request: {exc.message}", fix) from exc
        meta = {
            "owner": p.github_owner, "repo": p.github_repo, "branch": branch, "workflow_file": WORKFLOW_FILE,
            "dispatched_at": dispatched_at.isoformat(), "run_id": run_id, "cf_project": name, "subdomain": subdomain,
        }
        return DeployHandle(None, name, meta=meta)

    async def _latest_deployment(self, project: str, since: str | None) -> dict | None:
        async with self._client() as client:
            resp = await request(client, "Cloudflare", "GET", f"/pages/projects/{project}/deployments")
        for dep in resp.json().get("result", []):
            if since is None or dep.get("created_on", "") >= since[:19]:
                return dep
        return None

    async def get_status(self, deployment: Deployment) -> ProviderStatus:
        status = await self._tracker.status(deployment)
        if status.phase != PHASE_LIVE:
            return status
        dep = await self._latest_deployment(deployment.meta["cf_project"], deployment.meta.get("dispatched_at"))
        if dep is None:
            return ProviderStatus(PHASE_FAILED, "no_cloudflare_deployment", error="The workflow finished but Cloudflare has no new deployment.", meta=status.meta)
        stage = dep.get("latest_stage") or {}
        if stage.get("status") == "failure":
            return ProviderStatus(PHASE_FAILED, f"cloudflare:{stage.get('name')}:failure", error=f"Cloudflare stage '{stage.get('name')}' failed", meta=status.meta)
        status.deployment_id = dep["id"]
        status.meta["cf_deployment_url"] = dep.get("url")
        status.raw = f"cloudflare:{stage.get('name', 'deploy')}:{stage.get('status', 'success')}"
        return status

    async def get_logs(self, deployment: Deployment) -> list[LogLine]:
        lines = await self._tracker.logs(deployment, "github-actions")
        if deployment.deployment_id and deployment.meta.get("cf_project"):
            try:
                async with self._client() as client:
                    resp = await request(
                        client, "Cloudflare", "GET",
                        f"/pages/projects/{deployment.meta['cf_project']}/deployments/{deployment.deployment_id}/history/logs",
                    )
                for item in (resp.json().get("result") or {}).get("data", []) or []:
                    lines.append(LogLine(item.get("ts"), item.get("line", ""), "cloudflare:deployment"))
            except ApiError:
                pass  # Direct Upload deployments may not have Cloudflare-side build logs
        return lines

    async def get_outputs(self, deployment: Deployment) -> dict:
        async with self._client() as client:
            resp = await request(client, "Cloudflare", "GET", f"/pages/projects/{deployment.meta['cf_project']}")
        project = resp.json().get("result", {})
        subdomain = project.get("subdomain") or deployment.meta.get("subdomain")
        return {
            "public_url": f"https://{subdomain}" if subdomain else deployment.meta.get("cf_deployment_url"),
            "deployment_url": deployment.meta.get("cf_deployment_url"),
            "run_url": deployment.meta.get("run_url"),
        }

    async def destroy(self, deployment: Deployment) -> None:
        name = deployment.meta.get("cf_project") or deployment.provider_resource_id
        if not name:
            return
        async with self._client() as client:
            await request(client, "Cloudflare", "DELETE", f"/pages/projects/{name}", ok=(404,))
