"""GitHub Pages provider.

Repository -> enable Pages (build_type=workflow) -> commit .github/workflows/clouddeploy-pages.yml ->
workflow_dispatch -> Actions builds + actions/deploy-pages -> URL from GET /repos/{o}/{r}/pages.
"""
from __future__ import annotations

from datetime import datetime, timezone

from backend.models import Deployment
from backend.services.deployment.actions import ActionsRunTracker, build_steps
from backend.services.deployment.base import (
    DeployContext,
    DeployError,
    DeployHandle,
    DeploymentProvider,
    LogLine,
    ProviderStatus,
)
from backend.services.github.client import GitHubClient
from backend.services.http import ApiError

WORKFLOW_FILE = "clouddeploy-pages.yml"
WORKFLOW_PATH = f".github/workflows/{WORKFLOW_FILE}"
STATIC_TYPES = {"Static Frontend", "Frontend"}


def base_path(owner: str, repo: str) -> str:
    return "/" if repo.lower() == f"{owner.lower()}.github.io" else f"/{repo}/"


class GitHubPagesProvider(DeploymentProvider):
    key = "github_pages"

    def __init__(self, token_getter):
        self._token_getter = token_getter  # (user_id) -> str | None (the user's stored GitHub token)
        self._tracker = ActionsRunTracker(lambda dep: GitHubClient(self._token_getter(dep.user_id)))

    def missing_credentials(self) -> list[str]:
        return []  # uses the signed-in user's GitHub connection; checked in validate()

    async def check_credentials(self, user_id: int | None = None) -> dict:
        token = self._token_getter(user_id)
        if not token:
            return {"ok": False, "account": None, "error": "Connect GitHub to use GitHub Pages"}
        try:
            async with GitHubClient(token) as gh:
                user, scopes = await gh.get_user()
            missing = [s for s in ("repo", "workflow") if scopes and s not in scopes]
            return {"ok": not missing, "account": user["login"], "error": f"Token is missing scopes: {', '.join(missing)}" if missing else None}
        except ApiError as exc:
            return {"ok": False, "account": None, "error": str(exc)}

    def workflow(self, ctx: DeployContext) -> str:
        project = ctx.project
        steps, out = build_steps(ctx, base_path=base_path(project.github_owner or "", project.github_repo or ""))
        lines = [
            "# Generated by Git2Live: builds this repository and publishes it to GitHub Pages.",
            "name: Git2Live · GitHub Pages",
            "on:",
            "  workflow_dispatch:",
            "permissions:",
            "  contents: read",
            "  pages: write",
            "  id-token: write",
            "concurrency:",
            "  group: clouddeploy-pages",
            "  cancel-in-progress: false",
            "jobs:",
            "  build:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            *steps,
            "      - uses: actions/configure-pages@v5",
            "      - uses: actions/upload-pages-artifact@v3",
            "        with:",
            f"          path: {out if out.startswith('$') else repr(out)}",
            "  deploy:",
            "    needs: build",
            "    runs-on: ubuntu-latest",
            "    environment:",
            "      name: github-pages",
            "      url: ${{ steps.deployment.outputs.page_url }}",
            "    steps:",
            "      - id: deployment",
            "        uses: actions/deploy-pages@v4",
        ]
        return "\n".join(lines) + "\n"

    def validate(self, ctx: DeployContext) -> tuple[list[str], list[str]]:
        errors, warnings = [], []
        a = ctx.analysis
        if not ctx.github.authenticated:
            errors.append("Connect GitHub first. GitHub Pages deploys use your GitHub connection.")
        if not ctx.project.repository:
            errors.append("GitHub Pages publishes from a GitHub repository. Publish this project to GitHub first.")
        if a.get("app_type") not in STATIC_TYPES:
            errors.append(f"GitHub Pages only serves static sites. {a.get('framework')} ({a.get('app_type')}) needs a server.")
        if ctx.project.repo_private:
            errors.append("This repository is private. On GitHub Free, Pages is only available for public repositories.")
        if a.get("framework_key") not in {"static", "vite-react", "vite-vue", "vite-svelte", "vite", "create-react-app"} and a.get("app_type") in STATIC_TYPES:
            warnings.append("Make sure asset URLs are relative or use the /<repository>/ base path.")
        if ctx.config.env_vars:
            warnings.append("Environment variables are not used by GitHub Pages builds in this version.")
        return errors, warnings

    def preview(self, ctx: DeployContext) -> dict:
        project = ctx.project
        return {
            "resource": "GitHub Pages site (built by GitHub Actions)",
            "plan": "Free (public repository)",
            "build": "GitHub Actions",
            "build_command": ctx.pick("build_command") or "none (static files)",
            "output_dir": ctx.pick("output_dir") or ".",
            "base_path": base_path(project.github_owner or "", project.github_repo or ""),
            "generated_workflow": self.workflow(ctx) if project.repository else None,
            "repository_changes": [WORKFLOW_PATH, "Pages settings: source = GitHub Actions"],
        }

    async def deploy(self, ctx: DeployContext) -> DeployHandle:
        self.require_configured()
        p = ctx.project
        branch = ctx.config.branch or p.branch or "main"
        try:
            ctx.log("Enabling GitHub Pages with GitHub Actions as the source")
            await ctx.github.enable_pages_workflow(p.github_owner, p.github_repo)
            ctx.log(f"Committing {WORKFLOW_PATH} to {branch}")
            await ctx.github.put_file(
                p.github_owner, p.github_repo, WORKFLOW_PATH, self.workflow(ctx),
                "Add Git2Live GitHub Pages workflow", branch,
            )
            dispatched_at = datetime.now(timezone.utc)
            run_id = await ctx.github.dispatch_workflow(p.github_owner, p.github_repo, WORKFLOW_FILE, branch)
            ctx.log("Workflow dispatched" + (f" (run {run_id})" if run_id else ""))
        except ApiError as exc:
            fix = None
            if exc.status == 422 and "private" in exc.message.lower():
                fix = "Make the repository public or upgrade the GitHub plan to use Pages on private repositories."
            elif exc.status in (403, 404):
                fix = "Reconnect GitHub and grant the repo and workflow permissions."
            raise DeployError(f"GitHub rejected the request: {exc.message}", fix) from exc
        meta = {
            "owner": p.github_owner, "repo": p.github_repo, "branch": branch, "workflow_file": WORKFLOW_FILE,
            "dispatched_at": dispatched_at.isoformat(), "run_id": run_id,
        }
        return DeployHandle(str(run_id) if run_id else None, p.repository, meta=meta)

    async def get_status(self, deployment: Deployment) -> ProviderStatus:
        status = await self._tracker.status(deployment)
        if status.meta.get("run_id"):
            status.deployment_id = str(status.meta["run_id"])
        return status

    async def get_logs(self, deployment: Deployment) -> list[LogLine]:
        return await self._tracker.logs(deployment, "github-actions")

    async def get_outputs(self, deployment: Deployment) -> dict:
        meta = deployment.meta
        async with GitHubClient(self._token_getter(deployment.user_id)) as gh:
            pages = await gh.get_pages(meta["owner"], meta["repo"])
        return {"public_url": (pages or {}).get("html_url"), "run_url": meta.get("run_url")}

    async def destroy(self, deployment: Deployment) -> None:
        meta = deployment.meta
        async with GitHubClient(self._token_getter(deployment.user_id)) as gh:
            await gh.delete_pages(meta["owner"], meta["repo"])
