"""Netlify provider, using the official Netlify API (https://open-api.netlify.com/).

Source files (+ generated netlify.toml when the project has none) -> zip ->
POST /api/v1/sites (create site) -> POST /api/v1/sites/{id}/builds (Netlify Build API builds the zip
remotely) -> poll GET /api/v1/deploys/{deploy_id} -> site ssl_url.
"""
from __future__ import annotations

import httpx

from backend.config import settings
from backend.models import Deployment
from backend.services import workspace
from backend.services.deployment.base import (
    PHASE_BUILDING,
    PHASE_DEPLOYING,
    PHASE_FAILED,
    PHASE_LIVE,
    PHASE_QUEUED,
    DeployContext,
    DeployError,
    DeployHandle,
    DeploymentProvider,
    LogLine,
    ProviderStatus,
    slugify,
    unique_slug,
)
from backend.services.deployment.source import snapshot
from backend.services.http import ApiError, request

API = "https://api.netlify.com/api/v1"

STATE_MAP = {
    "new": PHASE_QUEUED, "pending_review": PHASE_QUEUED, "accepted": PHASE_QUEUED, "enqueued": PHASE_QUEUED,
    "retrying": PHASE_QUEUED, "building": PHASE_BUILDING, "uploading": PHASE_DEPLOYING,
    "uploaded": PHASE_DEPLOYING, "preparing": PHASE_DEPLOYING, "prepared": PHASE_DEPLOYING,
    "processing": PHASE_DEPLOYING, "processed": PHASE_DEPLOYING, "ready": PHASE_LIVE,
    "error": PHASE_FAILED, "rejected": PHASE_FAILED, "skipped": PHASE_FAILED,
}
SPA_KEYS = {"vite-react", "vite-vue", "vite-svelte", "vite", "create-react-app", "vue", "angular"}


def _fix_for(err: ApiError) -> str | None:
    if err.status == 401:
        return "NETLIFY_AUTH_TOKEN is invalid. Create a personal access token in Netlify → User settings → Applications."
    if err.status == 422:
        return "Netlify rejected the site settings. Try a different deployment name."
    if err.status == 429:
        return "Netlify rate limit reached. Wait a minute and try again."
    return None


class NetlifyProvider(DeploymentProvider):
    key = "netlify"

    def missing_credentials(self) -> list[str]:
        return [] if settings.netlify_auth_token else ["NETLIFY_AUTH_TOKEN"]

    def _client(self) -> httpx.AsyncClient:
        return httpx.AsyncClient(
            base_url=API, timeout=httpx.Timeout(120.0, connect=10.0),
            headers={"Authorization": f"Bearer {settings.netlify_auth_token}"},
        )

    async def check_credentials(self, user_id: int | None = None) -> dict:
        if not self.is_configured():
            return {"ok": False, "account": None, "error": "Provider Not Configured"}
        try:
            async with self._client() as client:
                user = (await request(client, "Netlify", "GET", "/user")).json()
            return {"ok": True, "account": user.get("email") or user.get("slug"), "error": None}
        except ApiError as exc:
            return {"ok": False, "account": None, "error": str(exc)}

    def _toml(self, ctx: DeployContext) -> str | None:
        """netlify.toml added to the uploaded zip only when the project doesn't have one."""
        if "netlify.toml" in (ctx.analysis.get("build_files") or []):
            return None
        a = ctx.analysis
        build = ctx.pick("build_command")
        if ctx.config.install_command and build:
            build = f"{ctx.config.install_command} && {build}"
        publish = ctx.pick("output_dir") or "."
        lines = ["# Generated by Git2Live", "[build]"]
        if build and a.get("needs_build", True):
            lines.append(f'  command = "{build}"')
        lines.append(f'  publish = "{publish}"')
        if a.get("package_manager"):
            lines += ["", "[build.environment]", '  NODE_VERSION = "20"']
        if a.get("framework_key") in SPA_KEYS:
            lines += ["", "[[redirects]]", '  from = "/*"', '  to = "/index.html"', "  status = 200"]
        return "\n".join(lines) + "\n"

    def validate(self, ctx: DeployContext) -> tuple[list[str], list[str]]:
        errors, warnings = [], []
        if ctx.project.source_type != "upload" and not ctx.project.repository:
            errors.append("Project has no source files.")
        if ctx.config.env_vars:
            warnings.append("Environment variables are not sent to Netlify in this version. Set them in the Netlify site settings.")
        if "netlify.toml" in (ctx.analysis.get("build_files") or []):
            warnings.append("Your existing netlify.toml controls the build command and publish directory.")
        return errors, warnings

    def preview(self, ctx: DeployContext) -> dict:
        toml = self._toml(ctx)
        return {
            "resource": "Netlify Site + Production Deploy",
            "plan": "Free",
            "build": "Netlify Build API (Netlify builds the uploaded source)",
            "build_command": ctx.pick("build_command") or "none (static files)",
            "output_dir": ctx.pick("output_dir") or ".",
            "root_dir": ctx.root_dir or None,
            "generated_netlify_toml": toml,
            "upload": "A zip of the validated source files is uploaded to Netlify.",
            "repository_changes": [],
        }

    async def deploy(self, ctx: DeployContext) -> DeployHandle:
        self.require_configured()
        files = await snapshot(ctx)
        toml = self._toml(ctx)
        archive = workspace.make_zip(files, {"netlify.toml": toml.encode()} if toml else None)
        async with self._client() as client:
            try:
                site_id = ctx.previous_resource_id
                if not site_id:
                    site = await self._create_site(client, ctx)
                    site_id = site["id"]
                    ctx.log(f"Created Netlify site '{site['name']}' ({site_id})")
                ctx.log(f"Uploading source zip ({len(archive) / 1024:.0f} KB) to the Netlify Build API")
                resp = await request(
                    client, "Netlify", "POST", f"/sites/{site_id}/builds",
                    data={"title": f"Git2Live: {ctx.project.name}"},
                    files={"zip": ("source.zip", archive, "application/zip")},
                )
            except ApiError as exc:
                raise DeployError(f"Netlify rejected the request: {exc.message}", _fix_for(exc)) from exc
        build = resp.json()
        deploy_id = build.get("deploy_id")
        ctx.log(f"Netlify build started: build {build.get('id')}, deploy {deploy_id}")
        return DeployHandle(deploy_id, site_id, meta={"build_id": build.get("id")})

    async def _create_site(self, client: httpx.AsyncClient, ctx: DeployContext) -> dict:
        base = ctx.config.name or ctx.project.name
        for name in (slugify(base, 60), unique_slug(base, 60), unique_slug(base, 60)):
            try:
                return (await request(client, "Netlify", "POST", "/sites", json={"name": name})).json()
            except ApiError as exc:
                if exc.status != 422:
                    raise
        raise DeployError("Could not find an available Netlify site name.", "Choose a different deployment name.")

    async def _deploy(self, deploy_id: str) -> dict:
        async with self._client() as client:
            return (await request(client, "Netlify", "GET", f"/deploys/{deploy_id}")).json()

    async def get_status(self, deployment: Deployment) -> ProviderStatus:
        if not deployment.deployment_id:
            return ProviderStatus(PHASE_QUEUED, "waiting")
        dep = await self._deploy(deployment.deployment_id)
        raw = dep.get("state", "unknown")
        phase = STATE_MAP.get(raw, PHASE_BUILDING)
        error = dep.get("error_message") if phase == PHASE_FAILED else None
        if phase == PHASE_FAILED and not error:
            error = f"Netlify deploy ended with state '{raw}'"
        return ProviderStatus(phase, raw, error=error)

    async def get_outputs(self, deployment: Deployment) -> dict:
        async with self._client() as client:
            site = (await request(client, "Netlify", "GET", f"/sites/{deployment.provider_resource_id}")).json()
        dep = await self._deploy(deployment.deployment_id) if deployment.deployment_id else {}
        return {
            "public_url": site.get("ssl_url") or site.get("url"),
            "deploy_url": dep.get("deploy_ssl_url"),
            "admin_url": site.get("admin_url"),
        }

    async def get_logs(self, deployment: Deployment) -> list[LogLine]:
        """Netlify's public API does not expose raw build logs; return the deploy's own summary."""
        if not deployment.deployment_id:
            return []
        dep = await self._deploy(deployment.deployment_id)
        lines = [LogLine(dep.get("created_at"), f"Deploy state: {dep.get('state')}", "netlify:deploy")]
        for msg in (dep.get("summary") or {}).get("messages", []) or []:
            text = " ".join(filter(None, [msg.get("title"), msg.get("description")]))
            lines.append(LogLine(dep.get("updated_at"), text, "netlify:summary", "error" if msg.get("type") == "error" else "info"))
        if dep.get("error_message"):
            lines.append(LogLine(dep.get("updated_at"), dep["error_message"], "netlify:deploy", "error"))
        if dep.get("admin_url") or dep.get("site_id"):
            lines.append(LogLine(None, f"Full build log: {dep.get('admin_url', 'Netlify dashboard')}/deploys/{deployment.deployment_id}", "netlify:deploy"))
        return lines

    async def destroy(self, deployment: Deployment) -> None:
        if not deployment.provider_resource_id:
            return
        async with self._client() as client:
            await request(client, "Netlify", "DELETE", f"/sites/{deployment.provider_resource_id}", ok=(404,))
